---
- name: Import AWG node keys check
  ansible.builtin.import_tasks: "{{ awg_roles_wg_tasks }}/host_keys_check.yml"

- name: Check AWG server config file on node
  ansible.builtin.stat:
    path: "{{ awg_dir }}/{{ awg_deploy_conf_basename }}"
  register: _wg_awg_server_conf_stat

- name: Check AWG Docker image
  ansible.builtin.command:
    argv: [docker, image, inspect, "{{ docker_image_name }}"]
  register: _wg_awg_image_inspect
  changed_when: false
  failed_when: false

- name: Check AWG server container
  ansible.builtin.command:
    argv:
      - docker
      - container
      - inspect
      - "-f"
      - "{{ '{{' }}.State.Running{{ '}}' }}"
      - "{{ docker_container_name }}"
  register: _wg_awg_container_running
  changed_when: false
  failed_when: false
